### ISSUE TITLE
Speed control

### ISSUE THREAD

**Issue by OttoVanluchene** [adrianlyjak/obsidian-aloud-tts#10]
Something you probably already are planning but can you add a setting to control the speed.

There is a speed option in the Whisper API:
speed: The speed of the generated audio. Select a value from 0.25 to 4.0. 1.0 is the default.

Thanks for the plugin btw was a missing piece in my workflow.

**Comment by adrianlyjak** [comment]
@OttoVanluchene Glad to hear it's working well for you! I'll look into adding speed controls, definitely seems useful.

**Comment by adrianlyjak** [comment]
Released in version 0.1.0

**Comment by OttoVanluchene** [comment]
Thanks for the quick addition!
