### ISSUE TITLE
Cache duration.

### ISSUE THREAD

**Issue by CGAlei** [adrianlyjak/obsidian-aloud-tts#33]
Hello Adrian, the plugin's cache duration of 168 hours is ideal to avoid additional charges for new inferences. I was unable to locate the hidden folder on my Windows system. Although I'm familiar with the process. The primary purpose is for backup. Is there a method to determine which portion of the text has been converted to audio? Any suggestions would be appreciated. Thanks for the plugin.

**Comment by adrianlyjak** [comment]
In the upcoming 0.3.0 release you'll be able to configure the cache duration. There's currently no good way to quickly see what's cached without perusing the `.tts` directory. What's your use case for monitoring the cache?

**Comment by CGAlei** [comment]
I dont want to delete the cache since this is the moiney i spent in Open AI, so i wa lloking for a way to store the audio in a folder, and never clean the cache

**Comment by adrianlyjak** [comment]
You can set your cache to effectively forever (876000 hours is 100 years), and keep it in your vault if configured like so:

<img width="752" alt="image" src="https://github.com/adrianlyjak/obsidian-aloud-tts/assets/2024018/8f4f07c9-50d8-476d-9fff-1908226d34ab">

> I was unable to locate the hidden folder on my Windows system. Although I'm familiar with the process. The primary purpose is for backup. 

Not sure why you're not seeing the .tts directory? Showing hidden folders can be tricky, are you sure you're following the right steps? The `.tts` directory should be right there at the top level of your vault. As an alternate path, it looks like there's a plugin that you can install with BRAT to view hidden files/folders: https://github.com/polyipseity/obsidian-show-hidden-files. 

Installing that, I see the following 

<img width="296" alt="image" src="https://github.com/adrianlyjak/obsidian-aloud-tts/assets/2024018/cb7915b0-1b08-4320-9b58-9dafabe8a101">

> Is there a method to determine which portion of the text has been converted to audio?

> I dont want to delete the cache since this is the moiney i spent in Open AI, so i wa lloking for a way to store the audio in a folder, and never clean the cache

It's not in my roadmap to get too detailed about getting too detailed with the cache. This field is moving fast, and I think in the near(ish) future there will be capable models that can be run device local. Then your requests will be effectively free.

**Comment by CGAlei** [comment]
Working, great works! this seems to be the only way to get OAI voices working fast in obsidian. Congratulations, and thanks for the explanation.

**Comment by adrianlyjak** [comment]
Glad you're finding it useful!
