### ISSUE TITLE
Help in using opendai with aloud plugin

### ISSUE THREAD

**Issue by fredjoe7** [adrianlyjak/obsidian-aloud-tts#36]
Need a quick guide to set it up with opendai.speech.

I am trying for 10 hours and opendai.speech is working but couldnt link it to aloud plugin yet.. 

I tried pasting the url and it gives parlor tts not found error.. while i have other tts (piper) set up...

**Comment by adrianlyjak** [comment]
Configuring a custom server is in "advanced" for a reason, it's somewhat experimental.

I'm not very familiar with openedai-speech, I just got it running enough to verify this plugin can be configured to connect to an external server. It looks like openedai-speech uses piper for `"model": tts-1` and xtts for `"model": tts-1-hd`. Those are the same model names that openai uses in their API, however currently this plugin only ever uses "tts-1," so I expect that is related to the error you're having with piper.

Looking through openedai-speech changes, it looks like they're experimenting with "Parler" tts, a recently released new TTS model. Perhaps you should try checking out an earlier tag on their git repo. There may be some broken stuff in development on their main branch. I seem to have just cloned `main` branch as well like you, but that was back in march 23, so I've been running [this bd3c7a6 version](https://github.com/matatonic/openedai-speech/tree/bd3c7a601a7193239cd68e9b2d3f069bacbc77e3) which works well for me. 

I would recommend first trying to make a curl request to the local server to debug it before integrating with the plugin

**Comment by fredjoe7** [comment]
managed to set it up..

aloud plugin doesnot read in reading mode ??

**Comment by adrianlyjak** [comment]
No, its integrated with the editor. I'm not sure how straightforward bbtaining text and selections from the reading mode is. Feel free to open another issue if that's a feature you think is important.
