### ISSUE TITLE
Feature Request: Read Note

### ISSUE THREAD

**Issue by kerim** [adrianlyjak/obsidian-aloud-tts#37]
Right now you have to select next and then run the command. I'd like to have a command that will just directly read the entirety of the current document, without having to first "select-all." Thanks.

**Comment by adrianlyjak** [comment]
@kerim which version are you running? Can you clarify what you mean by "Right now you have to select next and then run the command?" I've slightly tweaked this behavior in the last few versions. It should read the whole document if nothing is selected, or the cursor is at the start of the document. Or do you have something else in mind?

**Comment by adrianlyjak** [comment]
There's 4 possible ways to trigger the audio to play a new selection:

1. the ribbon icon
<img width="69" alt="Screenshot 2024-05-19 at 9 00 41 PM" src="https://github.com/adrianlyjak/obsidian-aloud-tts/assets/2024018/1fd8fe31-a968-4639-92ce-ec87bf73eba1">

2. Editor command "Play selection"
<img width="590" alt="image" src="https://github.com/adrianlyjak/obsidian-aloud-tts/assets/2024018/4fad3085-7fa7-4e46-a5d4-53f2e5034796">

3. Right click to play

<img width="340" alt="image" src="https://github.com/adrianlyjak/obsidian-aloud-tts/assets/2024018/42308553-18e9-4106-bed1-b4c3eedf9b60">

4. Or, if the toolbar is open, hitting the big play button

<img width="370" alt="image" src="https://github.com/adrianlyjak/obsidian-aloud-tts/assets/2024018/816291de-ffc2-473e-977b-e17bfa6cdfb2">


I'm noticing that "#2" could be  improved, it currently requires your cursor to be entered into the file before the command is available. Is perhaps what you're having trouble with? Or is it something else.

**Comment by kerim** [comment]
Thanks. It is working now. 

Some suggestions:

When using #2, the pause/play buttons show up, but not when using #1. That would be good, as I and to use the command palette to stop it when testing just now.

When using #3, if nothing is selected, it will select the current word and just play that. So here it would be good to have a "play note" option as well.

**Comment by adrianlyjak** [comment]
> I'm noticing that #2 could be improved, it currently requires your cursor to be entered into the file before the command is available. Is perhaps what you're having trouble with? Or is it something else.

Just released some improvements here in 0.4.0 which will let that "Play selection" command play the full file

> When using https://github.com/adrianlyjak/obsidian-aloud-tts/issues/2, the pause/play buttons show up, but not when using https://github.com/adrianlyjak/obsidian-aloud-tts/issues/1. That would be good, as I and to use the command palette to stop it when testing just now.

You can configure the player to stay open in the settings. By default that's mobile only

<img width="568" alt="image" src="https://github.com/adrianlyjak/obsidian-aloud-tts/assets/2024018/1063317c-4c09-4307-bad1-a275ac2bde8b">

> When using https://github.com/adrianlyjak/obsidian-aloud-tts/issues/3, if nothing is selected, it will select the current word and just play that. So here it would be good to have a "play note" option as well.

Thanks, I'll look into that further and see if it can be improved. I might be inclined to just make it run the full file if the selection is extremely short, assuming the selection was a mistake

**Comment by kerim** [comment]
Seems to be working as expected now. Thanks
