### ISSUE TITLE
Feature Request: Skip Markup

### ISSUE THREAD

**Issue by kerim** [adrianlyjak/obsidian-aloud-tts#38]
I use three kinds of markup in my documents: 

- Better Bibtex Citekeys (wrapped in square brackets `[ @authortitleyear, page ]` )
- Markdown footnotes (also wrapped in square brackets, but with a caret symbol `[^1]`)
- CriticMarkup text for suggestions and comments in markdown  (wrapped in curly brackets and angle brackets `{>> notes to self <<}`)

I would like to have Aloud skip text wrapped in these markup code when reading my document, as it would make reading much more fluid without all my notes and citations. Thanks.

**Comment by adrianlyjak** [comment]
The current version of the plugin should handle your second case. It strips markdown in general. 

I can add your other cases, seems harmless. I'm sure there's countless other formats that this could be stripping, makes me want a more elegant solution here, like if it could grab the rendered text somehow, but for now I'll just add the new case.

**Comment by kerim** [comment]
Thanks. It doesn’t yet work for me in version 0.3.0, but I'll check again after the next update is released.

**Comment by adrianlyjak** [comment]
Released just now in 0.4.0

**Comment by kerim** [comment]
Working great. Thanks so much!
