### ISSUE TITLE
Feature Request: bind Pause and Resume hotkeys into one Pause/Resume hotkey

### ISSUE THREAD

**Issue by xujialiu** [adrianlyjak/obsidian-aloud-tts#40]
Pause and Resume functionality is very commonly used, but setting Pause and Resume to two different hotkeys is not very reasonable, as it creates a disjointed experience by requiring different keys each time. Most media players bind Pause and Resume to the same hotkey. I hope you can modify this feature. 

Thank you very much.

**Comment by adrianlyjak** [comment]
Thanks! You make good points. This is also easy to implement
