### ISSUE TITLE
Feature Request: 1.15 speed

### ISSUE THREAD

**Issue by kerim** [adrianlyjak/obsidian-aloud-tts#45]
I find 1.0 speed too slow, and 1.25 too fast. Wondering if we could have the option to set the speed manually or have a 1.15 option? Thanks.

**Comment by xujialiu** [comment]
You can modify the plugin's settings file to customize the playback speed. The settings file is located at `.obsidian/plugins/aloud-tts/data.json`:

```
{
  "OPENAI_API_KEY": "sk-you_api_key",
  "OPENAI_API_URL": "",
  "model": "tts-1",
  "ttsVoice": "nova",
  "chunkType": "sentence",
  "playbackSpeed": 1.15,
  "cacheDurationMillis": 10000,
  "cacheType": "local",
  "showPlayerView": "always"
}
```

You can set the `playbackSpeed` to any speed you want. After saving the `data.json` file, restart your obsidian app, the speed rate should be taken effect.

**Comment by xujialiu** [comment]
Actually, it would be easier for most users if the extension can provide hotkeys to speed up and down by increasing the speed rate by 0.1 and provide a UI like the picture below.
![image](https://github.com/adrianlyjak/obsidian-aloud-tts/assets/46064313/9098b40c-3dcf-4396-b277-adf1f029926f)
