### ISSUE TITLE
Can you add the feature for custom models?

### ISSUE THREAD

**Issue by qidianlinjin1990** [adrianlyjak/obsidian-aloud-tts#49]
Can you add the feature for custom models? Like tts-1 hd, and some providers support OpenAI format, so by customizing other models, you can use other tts models.Thank you

**Comment by adrianlyjak** [comment]
@qidianlinjin1990 I'd like to support more providers, ideally with minimal effort and reasonable future proofing. Which providers that support OpenAI format do you have in mind? Right now, you can change the openai base url. Might that work for your use case? There's likely a few customizations required to make it fully configurable, such as the voice quality as you've mentioned, as well as modifying the model voice parameter. Having an example of some of the APIs you want to integrate would be helpful so I can design the customization elegantly.

**Comment by qidianlinjin1990** [comment]
Thank you! A supplier called siliconcloud is set to release an open-source TTS model this month. Their website is https://siliconflow.cn/siliconcloud. They have always supported the OpenAI format, and their models are quite comprehensive, including chat, embedding, rerank, and audio models.
