### ISSUE TITLE
Highlight text correctly, even if its changed

### ISSUE THREAD

**Issue by adrianlyjak** [adrianlyjak/obsidian-aloud-tts#5]
1. I want to be able to edit text as its speaking to me, and not break the editor highlighting
2. If the text is ahead of the reader, I want the reader to read the new text
3. If a text chunk is repeated, I want the editor to correctly highlight the repeated chunk, even if its after the first one

**Comment by Calorion** [comment]
Also, if you edit text, and then hit the "back" button, it reads the old text, not the edited text.
