### ISSUE TITLE
Audio distortion between tracks, and OS track seeking

### ISSUE THREAD

**Issue by adrianlyjak** [adrianlyjak/obsidian-aloud-tts#57]
The current audio mechanism updates an html5 audio element with each piece of text, resetting the position to 0 on each track switch. This can cause audio distortion between tracks. Additionally this cause the OS level seek functionality to not work well (you can’t go back, or past the next sentence).

**Comment by MiracleBlue** [comment]
I see we're using ManagedMediaSource API for much of this at the moment, correct?  It may perhaps be more reliable to use the MediaSession API to hook into media control events.  I'll play with this a little and see what happens.

**Comment by adrianlyjak** [comment]
Oh nice! I wasn’t aware of the media session api.

I think there’s a pretty clear cause to the distortion: I’m resetting the playback position to 0 for each track, while simultaneously resetting the audio to the new track. The more correct behavior is to instead append the audio, so that it can continue playing. This is doable, there’s just some audio loading classes that need a refactor and I haven’t gotten around to it.

From what I’m reading, the media session api is more about interacting with the operating system to display metadata and to intercept commands (seek, skip). I’m not seeing any parts of it that are related to running audio. That being said, I could potentially go back to the web audio API rather than html MediaSource, and use MediaSession to interact with the OS… I was however having intermittent buggy behavior with iOS just not playing with web audio.

Either way, I was wondering how to intercept skip track commands and set the audio track title, so this is awesome! If you end up trying it out, I’d love to hear about your findings or if you have any recommended changes

**Comment by MiracleBlue** [comment]
Sorry my bad, I thought this issue was about the media events.  Yeah I've been working at fixing the funny little skip in my local actually :D I'll see what happens, if I do manage to come up with something I'll make a PR!
