### ISSUE TITLE
Background audio in mobile

### ISSUE THREAD

**Issue by adrianlyjak** [adrianlyjak/obsidian-aloud-tts#6]
When running the player on a mobile device, such as on an iphone, I want the text player to continue to play while the device is locked, and show an OS level play-pause-track-switcher

**Comment by faixal5882** [comment]
> When running the player on a mobile device, such as on an iphone, I want the text player to continue to play while the device is locked, and show an OS level play-pause-track-switcher

Were you able to achieve this. This will be a game changing.

**Comment by adrianlyjak** [comment]
Fixed in #51, will release later this week. I'll also announce in the obsidian discord in the extensions updates channel when its released

**Comment by adrianlyjak** [comment]
Note that there are some minor issues with the new implementation that will take another overhaul of some of the internals
- occasional clipping/distortion sounds between sentence "tracks"
- OS level track seeking does not work well
- On ios, I can play over different audio devices, but there's significant latency between tracks with airplay
